version: '3.11'
x-environment: &commonEnvironment
  - APP_PORT=${APP_PORT}
  - DEBUG=${DEBUG}
  - ALLOWED_HOSTS=${ALLOWED_HOSTS}
  - DATABASE_NAME=${DB_NAME}
  - DATABASE_USER=${DB_USER}
  - DATABASE_PASSWORD=${DB_PASSWORD}
  - DATABASE_HOST=${DB_HOST}
  - DATABASE_PORT=${DB_PORT}
  - ADMIN_USERNAME=${ADMIN_USERNAME}
  - ADMIN_EMAIL=${ADMIN_EMAIL}
  - ADMIN_PASSWORD=${ADMIN_PASSWORD}
  - CELERY_BROKER=${CELERY_BROKER}
  - SECRET_KEY=${SECRET_KEY}
  - EMAIL_HOST=${EMAIL_HOST}
  - EMAIL_USE_TLS=${EMAIL_USE_TLS}
  - EMAIL_PORT=${EMAIL_PORT}
  - EMAIL_USE_SSL=${EMAIL_USE_SSL}
  - EMAIL_HOST_USER=${EMAIL_HOST_USER}
  - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}
  - EMAIL_SENDER=${EMAIL_SENDER}

services:

  application:
    build: .
    
    environment: *commonEnvironment

    env_file:
      - .env

    ports:
      - "8005:${APP_PORT}"

    command: sh -c "/opt/venv/bin/python manage.py collectstatic &&
                    /opt/venv/bin/gunicorn bizcore.wsgi:application --bind 0.0.0.0:${APP_PORT}"
