version: '3.11'
services:
  application:
    build: .
    environment:
      - PORT=8111
    env_file:
      - .env
    ports:
      - "8111:8111"
    command: sh -c "/opt/venv/bin/gunicorn bizcore.wsgi:application --bind 0.0.0.0:${APP_PORT}"
