# Generated by Django 4.2.2 on 2023-06-21 09:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('platform', models.CharField(choices=[('Web', 'Web'), ('Mobile', 'Mobile')], max_length=255)),
                ('repository_url', models.CharField(max_length=300)),
                ('production_url', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('Initiated', 'Initiated'), ('Planning', 'Planning'), ('In-Progress', 'In-Progress'), ('On-Hold', 'On-Hold'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], max_length=55)),
                ('commence_date', models.DateTimeField()),
                ('completion_date', models.DateTimeField()),
                ('release_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('parent_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customized_projects', to='project.project')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ('-created_at',),
            },
        ),
    ]
