# Generated by Django 4.2.2 on 2023-06-22 11:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    replaces = [('project', '0001_initial'), ('project', '0002_alter_project_status'), ('project', '0003_alter_project_commence_date_and_more'), ('project', '0004_alter_project_created_by')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('platform', models.CharField(choices=[('Web', 'Web'), ('Mobile', 'Mobile')], max_length=255)),
                ('repository_url', models.CharField(max_length=300)),
                ('production_url', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(choices=[('Initiated', 'Initiated'), ('Planning', 'Planning'), ('In-Progress', 'Inprogress'), ('On-Hold', 'Onhold'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Initiated', max_length=55)),
                ('commence_date', models.DateField()),
                ('completion_date', models.DateField(null=True)),
                ('release_date', models.DateField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('parent_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customized_projects', to='project.project')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ('-created_at',),
            },
        ),
    ]
