# Generated by Django 4.2.2 on 2023-06-21 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_project_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='commence_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='completion_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='production_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='release_date',
            field=models.DateField(null=True),
        ),
    ]
