# Generated by Django 4.2.2 on 2023-07-10 09:24

from django.db import migrations, models
import subscription.models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0006_alter_invoice_generated_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_no',
            field=models.AutoField(default=subscription.models.get_initial_invoice_number, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='tax_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total_tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11),
        ),
    ]
